var apiKey = 'psc1Xsy0IW';
var baseurl = 'https://evds2.tcmb.gov.tr/service/evds/';

List<String> series = [
  'USD',
  'EUR',
  'AUD',
  'BGN',
  'CAD',
  'CHF',
  'CNY',
  'DKK',
  'GBP',
  'IRR',
  'ITL',
  'JPY',
  'KWD',
];

Map<String, String> seriesNames = {
  'USD': 'ABD Doları',
  'EUR': 'Euro',
  'ATS': 'Avusturya Şilini',
  'AUD': 'Avusturalya Doları',
  'BEF': 'Belçika Frangı',
  'BGN': 'Bulgar Levası',
  'CAD': 'Kanada Doları',
  'CHF': 'İsviçre Frangı',
  'CNY': 'Çin Yuanı',
  'DEM': 'Alman Markı',
  'DKK': 'Danimarka Kronu',
  'ECU': 'Ecu',
  'ESP': 'İspanyol Pezetası',
  'FIM': 'Finlandiya Markkası',
  'FRF': 'Fransız Frangı',
  'GBP': 'İngiltere Sterlini',
  'GRD': 'Yunan Drahmisi',
  'IEP': 'İrlanda Lirası',
  'IRR': '100 İran Riyali',
  'ITL': 'İtalyan Lireti',
  'JPY': 'Japon Yeni',
  'KWD': 'Kuveyt Dinarı',
  'LUF': 'Lüksemburg Frangı',
  'NLG': 'Hollanda Florini',
  'NOK': 'Norveç Kronu',
  'PKR': 'Pakistan Rupisi',
  'PTE': 'Portekiz Esküdosu',
  'QAR': 'Katar Riyali',
  'RON': 'Rumeny Leyi',
  'RUB': 'Rus Rublesi',
  'SAR': 'S.Arabistan Riyali',
  'SEK': 'İsveç Kronu',
};
